name: CI

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ubuntu Packages
        run: |
          sudo apt-get update
          sudo apt-get install valgrind

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip mypy
          pip install setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Type checking with mypy
        run: mypy --ignore-missing-imports ValgrindCI/*.py

      - name: Build and Install
        run: |
          touch ValgrindCI/py.typed
          python setup.py bdist_wheel
          pip install ValgrindCI --no-index -f dist/ValgrindCI*.whl

      - name: Test
        working-directory: build
        run: |
          cmake -DCMAKE_C_FLAGS_DEBUG="-g -Wall" -DCMAKE_BUILD_TYPE=Debug ../tests
          make
          valgrind --tool=memcheck --xml=yes --xml-file=test.xml ./test_basic
          ctest --output-on-failure

  semgrep:
    uses: ppizarror/workflow-actions/.github/workflows/semgrep.yml@master
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}