name: Test Python Package

on: [push]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Ubuntu Packages
      run: |
        sudo apt-get update
        sudo apt-get install valgrind
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build and Install
      run: |
        python setup.py bdist_wheel
        pip install ValgrindCI --no-index -f dist/ValgrindCI*.whl
    - name: Test
      run: |
        mkdir build
        cd build
        cmake ../tests
        make
        ctest
